language: python
dist: xenial
sudo: true

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install: :
  - pip install pipenv
  - pip install sync -d

script:
  - pipenv run falke8
  - pipenv run pytest --cov=sistex

after_success:
  - codecov
