language: python
dist: xenial
sudo: true

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  global:
    - system
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install: :
  - pip install pipenv
  - pip install sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb" -U postgres
script:
  - pipenv run falke8
  - pipenv run pytest --cov=sistex

after_success:
  - codecov
